def generate_report(prediction, confidence):
    confidence = float(confidence)
    return f"""
    AI Dermatology Screening Report

    Predicted Condition: {prediction}
    Confidence Score: {confidence * 100:.2f}%

    This result is generated by an AI-based classification model.
    This is not a medical diagnosis.

    Please consult a certified dermatologist for confirmation.
    """