def generate_report(
    prediction,
    confidence,
    risk_level,
    is_uncertain,
    uncertainty_message,
    recommendations,
):
    confidence = float(confidence)

    uncertainty_section = ""
    if is_uncertain and uncertainty_message:
        uncertainty_section = f"""
    Result Certainty: Uncertain
    Uncertainty Notice: {uncertainty_message}
    """
    else:
        uncertainty_section = """
    Result Certainty: Acceptable
    """

    return f"""
    AI Dermatology Screening Report

    Predicted Condition: {prediction}
    Confidence Score: {confidence * 100:.2f}%
    Risk Level: {risk_level.capitalize()}
    {uncertainty_section}

    Recommendation:
    {recommendations}

    This result is generated by an AI-based classification model.
    This is not a medical diagnosis.

    Please consult a certified dermatologist for confirmation.
    """